version: 2
jobs:
  build:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build Project luna-site
          command: cd luna-frontend && yarn install && CI=false yarn build 
      - run:
          name: Install & Build project luna-api
          command: cd luna-api && yarn install
      - run: 
          name: Test Project
          command: echo "This Test Space"
      - setup_remote_docker: 
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.12.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Build and Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            SITE=site-$(git rev-parse --short HEAD)
            docker build -t penthaizza/lunaproject:echo $SITE ./luna-frontend
            docker tag penthaizza/lunaproject:echo $SITE penthaizza/lunaproject:site-latest
            docker push penthaizza/lunaproject
            API=api-$(git rev-parse --short HEAD)
            docker build -t penthaizza/lunaproject:echo $API ./luna-api
            docker tag penthaizza/lunaproject:echo $API penthaizza/lunaproject:api-latest 
            docker push penthaizza/lunaproject
  deploy-to-dev:
    machine: true
    steps:
      - run: 
          name: Deploy to DEV-Site-Server
          command: | 
            sudo apt-get update
            sudo apt-get install sshpass
            sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$SERVER_HOST "ls -a && sudo docker rm -f luna-site && sudo docker image prune -a -f && sudo docker run -d -p 3000:3000 -p 22200:22200 -p 17000:17000 --name luna-site penthaizza/lunaproject:site-$(git rev-parse --short HEAD)"
      - run:
          name: Deploy to DEV-API-Server
          command: sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$SERVER_HOST "ls -a && sudo docker rm -f luna-api && sudo docker image prune -a -f && sudo docker run -d -e "PORT=3020" -e "PROJECT_NAME=luna-api" -p 3020:3020 -p 22202:22202 -p 17002:17002 --name luna-api penthaizza/lunaproject:api-$(git rev-parse --short HEAD)"
  deploy-to-prod:
    machine: true
    steps:
      - run: 
          name: Deploy to Prod-Site-Server
          command: | 
            sudo apt-get update
            sudo apt-get install sshpass
            sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$PROD_SERVER "ls -a && sudo docker rm -f luna-site && sudo docker image prune -a -f && sudo docker run -d -p 3000:3000 -p 22200:22200 -p 17000:17000 --name luna-site penthaizza/lunaproject:site-$(git rev-parse --short HEAD)"
      - run:
          name: Deploy to Prod-API-Server
          command: sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$PROD_SERVER "ls -a && sudo docker rm -f luna-api && sudo docker image prune -a -f && sudo docker run -d -e "PORT=3020" -e "PROJECT_NAME=luna-api" -p 3020:3020 -p 22202:22202 -p 17002:17002 --name luna-api penthaizza/lunaproject:api-$(git rev-parse --short HEAD)"
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy-to-dev:
          requires:
            - build
          filters:
            branches:
                only: develop
      - deploy-to-prod:
          requires:
            - deploy-to-dev
          filters:
            branches:
                only: develop